INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (121, '210 - I', 4, 119, 21);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (122, 'ABACAXIS', 4, 120, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (123, 'ACARAZINHO', 4, 121, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (124, 'ÁGUA AZUL - PARTE A', 4, 122, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (125, 'AGUAÇU', 4, 123, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (126, 'ALTO PIXUNA', 4, 124, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (127, 'ANAJÁ', 4, 125, 27);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (128, 'ANGICO', 4, 126, 27);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (129, 'ARACÁ', 4, 127, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (130, 'ARAGUAXIM', 4, 128, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (132, 'ARARANDEUA - PARTE A', 4, 130, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (133, 'ARICA - AÇU', 4, 131, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (134, 'ARRAIAS', 4, 132, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (135, 'ARURI', 4, 133, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (136, 'AUTAZ II', 4, 134, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (137, 'BAIXO MARI', 4, 135, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (138, 'BALBINA', 4, 136, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (139, 'BARAUANA', 4, 137, 21);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (140, 'BARRANQUEIRA-15A', 4, 138, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (141, 'BATOVI -06', 4, 139, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (142, 'BOA ESPERANCA-C', 4, 140, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (144, 'BOM PRINCÍPIO PARTE A E B', 4, 142, 22);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (145, 'BORECAIA', 4, 143, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (146, 'BR-070', 4, 144, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (147, 'BR-210 - II', 4, 145, 21);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (148, 'BRANQUINHO', 4, 146, 21);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (151, 'BUIUÇU', 4, 149, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (152, 'BUJARU', 4, 150, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (153, 'BURAREIRO', 4, 151, 22);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (154, 'BURITI', 4, 152, 22);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (155, 'BURITI - PARTE B E C', 4, 153, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (156, 'BURITI FIGURA 06', 4, 154, 22);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (157, 'CABALIANA', 4, 155, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (158, 'CABIXI', 4, 156, 22);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (159, 'CACHOEIRA DE SAMUEL', 4, 157, 22);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (161, 'CACHOEIRINHA', 4, 159, 27);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (162, 'CAETANO DIAS', 4, 160, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (163, 'CAMATIÁ', 4, 161, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (164, 'CAMBURÃO', 4, 162, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (166, 'CAMPINARANA II', 4, 164, 1);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (167, 'CAMPO LIMPO', 4, 165, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (168, 'CANAÃ - DISCRIMINATORIA JUDICIAL', 4, 166, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (169, 'CAPIM', 4, 167, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (170, 'CAPITÃO POÇO', 4, 168, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (171, 'CARACARAÍ', 4, 169, 21);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (173, 'CARACARANÃ', 4, 171, 21);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (176, 'CARAJÁS II', 4, 174, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (178, 'CARANDA GUANANDI -02', 4, 176, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (179, 'CARAPÁ', 4, 177, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (181, 'CARIPÉ', 4, 179, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (182, 'CARLINDA', 4, 180, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (183, 'CASSIPORÉ', 4, 181, 4);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (185, 'CASTANHO', 4, 183, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (186, 'CASTRO ALVES', 4, 184, 22);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (188, 'CHÁCARA MARCON', 4, 186, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (191, 'COLONE', 4, 189, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (206, 'CORIXÃO', 4, 204, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (207, 'CORUMBIÁRA', 4, 205, 22);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (209, 'CORUMBIARA SETOR PARECIS', 4, 207, 22);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (212, 'CUNHA DO MARECHAL', 4, 210, 22);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (214, 'CUPARI', 4, 212, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (216, 'D - JARU UARÚ', 4, 214, 22);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (228, 'DIAMANTINO', 4, 226, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (229, 'DIVISA', 4, 227, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (232, 'ESTIVADO - A', 4, 230, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (233, 'ESTIVADO - B', 4, 231, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (234, 'ESTRELA', 4, 232, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (235, 'F. B. CENTRAL', 4, 233, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (236, 'FAZENDA ANGELI   I', 4, 234, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (237, 'FAZENDA ARNO', 4, 235, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (238, 'FAZENDA DIVISA', 4, 236, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (239, 'FAZENDA ENCONSTA VERDE', 4, 237, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (240, 'FAZENDA FUJI', 4, 238, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (242, 'FAZENDA LAGOA BONITA', 4, 240, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (243, 'FAZENDA LEITNER', 4, 241, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (244, 'FAZENDA LEONANRDO III', 4, 242, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (246, 'FAZENDA MOEMA', 4, 244, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (247, 'FAZENDA NETO', 4, 245, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (248, 'FAZENDA NOSSA SENHORA APARECIDA', 4, 246, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (249, 'FAZENDA R.A', 4, 247, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (250, 'FAZENDA ROSATI', 4, 248, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (251, 'FORMIGA', 4, 249, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (253, 'FORMOSO', 4, 251, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (254, 'GAMA SETOR A E B', 4, 252, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (258, 'GAMELEIRA', 4, 256, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (259, 'GARÇAS-A', 4, 257, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (260, 'GARÇAS-D', 4, 258, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (261, 'GELADINHO - PARTE A', 4, 259, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (263, 'GUAMÁ I', 4, 261, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (266, 'GUAPORÉ', 4, 264, 22);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (270, 'GURUPI-MIRIM', 4, 268, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (271, 'GURUPIZINHO', 4, 269, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (272, 'IGARAPÉ SUJO', 4, 270, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (276, 'IMOVEL MUCUIM', 4, 274, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (277, 'INFERNINHO', 4, 275, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (279, 'IPORÁ', 4, 277, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (281, 'IQUÊ', 4, 279, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (282, 'IRANDUBA - PIC BELA VISTA', 4, 280, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (283, 'JANAUACÁ', 4, 281, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (284, 'JANDIATUBA', 4, 282, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (287, 'JAURU - I', 4, 285, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (288, 'JAURU - III', 4, 286, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (289, 'JAVARI', 4, 287, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (290, 'JURUEMA', 4, 288, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (291, 'JURUENA - II', 4, 289, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (292, 'JURUTI VELHO', 4, 290, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (293, 'LIBERDADE - FIGURA I', 4, 291, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (294, 'LOTEAMENTO  TABOCÃO', 4, 292, 27);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (297, 'LUCAS RIO VERDE', 4, 295, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (298, 'MACACO', 4, 296, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (299, 'MAIOR', 4, 297, 27);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (303, 'MAMORI', 4, 301, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (304, 'MÁRIO LOBÃO', 4, 302, 1);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (305, 'MARTINS - 02', 4, 303, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (306, 'MASSACO', 4, 304, 22);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (309, 'MATAPI-CURIAÚ-VILA - NOVA  AD04', 4, 307, 4);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (311, 'MATRINXÃ-05', 4, 309, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (312, 'MATRINXA-6', 4, 310, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (313, 'MESTRE -01', 4, 311, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (314, 'MIRASSOL - ÁREA 2', 4, 312, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (315, 'MIRASSOL - LOTE PRIMAVERA', 4, 313, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (316, 'MISTERIOSA', 4, 314, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (318, 'MONTE NEGRO-05', 4, 316, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (319, 'MOTORISTA', 4, 317, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (322, 'MURURÉ', 4, 320, 4);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (323, 'MUTUNGA', 4, 321, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (325, 'NHANDU', 4, 323, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (327, 'NIQUIÁ', 4, 325, 21);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (328, 'NORMANDIA', 4, 326, 21);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (329, 'NOVO AXIOMA/REDENÇÃO', 4, 327, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (330, 'NOVO PARAISO', 4, 328, 21);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (331, 'ONÇA MAGRA-II', 4, 329, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (332, 'OURO BRANCO', 4, 330, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (333, 'OURO PRETO', 4, 331, 22);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (336, 'PACAJAZINHO', 4, 334, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (337, 'PADRONAL- A', 4, 335, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (338, 'PARAISO', 4, 336, 22);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (339, 'PARECIS', 4, 337, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (340, 'PAREDAO-01', 4, 338, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (341, 'PAU D ARCO', 4, 339, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (342, 'PAU DE REMO', 4, 340, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (343, 'PAUINI', 4, 341, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (345, 'PENETECAUA', 4, 343, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (346, 'PIC BELA VISTA  II', 4, 344, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (347, 'PIOLHINHO -B', 4, 345, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (349, 'PITINGA - PARTE 2', 4, 347, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (351, 'PITINGA 5', 4, 349, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (352, 'POENTE', 4, 350, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (353, 'PORTO LUIZ - MAT. 847', 4, 351, 1);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (354, 'PRIMAVERA', 4, 352, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (357, 'PROVIDÊNCIA', 4, 355, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (358, 'PURETÊ', 4, 356, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (360, 'PURUS', 4, 358, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (363, 'QUILOMBO', 4, 361, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (364, 'RECANTO SAUI', 4, 362, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (365, 'REPARTIMENTO - PARTE 2', 4, 363, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (366, 'RIBEIRÃO CAFÉ - FIGURA -6', 4, 364, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (368, 'RIBEIRÃO CAFÉ -04', 4, 366, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (369, 'RIBEIRÃO DAS POMBAS', 4, 367, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (371, 'RIBEIRAO DOS COCAIS', 4, 369, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (373, 'RIBEIRÃO MARA', 4, 371, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (374, 'RIO ALTO', 4, 372, 22);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (375, 'RIO JARU', 4, 373, 22);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (378, 'RIO MADEIRA II', 4, 376, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (380, 'RIO MARIA I E II', 4, 378, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (381, 'RIO NOVO', 4, 379, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (384, 'RIO PARDO', 4, 382, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (385, 'RIO PRETO', 4, 383, 22);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (386, 'RIO VERDE- I', 4, 384, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (388, 'S/NOME', 4, 386, 27);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (464, 'SALOBRA- II', 4, 462, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (465, 'SALTO', 4, 463, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (466, 'SAMAUMA', 4, 464, 22);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (468, 'SANTA CRUZ', 4, 466, 22);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (474, 'SÃO BENEDITO', 4, 472, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (475, 'SÃO CARLOS - LOTE CELESTE', 4, 473, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (478, 'SÃO JOÃO  - FIGURA B', 4, 476, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (479, 'SÃO JOÃO - FIGURA - A', 4, 477, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (480, 'SÃO PEDRO', 4, 478, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (481, 'SEM NOME', 4, 479, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (485, 'SEPOTUBA-II', 4, 483, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (486, 'SERENA - SUSSUAPARA E PEDRA CUMPRIDA', 4, 484, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (488, 'SERINGA B', 4, 486, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (489, 'SERINGAL NOVO DESTINO', 4, 487, 1);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (490, 'SERINGAL PORTO MAMURIÁ', 4, 488, 1);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (492, 'SERINGAL SAGADO/IPIRANGA', 4, 490, 1);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (493, 'SERRA DAS ARARAS -I', 4, 491, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (494, 'SERRA DO TAQUARUÇU', 4, 492, 27);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (495, 'SERRA NOVA FIG.  01', 4, 493, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (496, 'SERRA NOVA II', 4, 494, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (498, 'SONHO AZUL', 4, 496, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (499, 'SOROROZINHO I, II E III', 4, 497, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (500, 'SUCURUINA - IE', 4, 498, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (501, 'SUCURUINA-IIE', 4, 499, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (502, 'SURUBIM', 4, 500, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (504, 'TACANA', 4, 502, 3);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (506, 'TAMANDUA', 4, 504, 22);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (507, 'TAMBORIM', 4, 505, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (508, 'TAPARÁ', 4, 506, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (509, 'TAQUARÁ', 4, 507, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (510, 'TAQUARAL', 4, 508, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (511, 'TARTARUGAL GRANDE', 4, 509, 4);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (517, 'TAUÁ', 4, 515, 27);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (519, 'TELES PIRES', 4, 517, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (521, 'TEPEQUEM', 4, 519, 21);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (523, 'TERRA FIRME', 4, 521, 22);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (527, 'TERRA SANTA', 4, 525, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (532, 'TIPIRATINS', 4, 530, 27);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (533, 'TOCANTINS', 4, 531, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (534, 'TRAIRÃO', 4, 532, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (537, 'TRANSAMAZÖNICA', 4, 535, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (538, 'TUBARÃO', 4, 536, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (539, 'TUCUNARÉ', 4, 537, 4);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (540, 'TUERÊ', 4, 538, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (541, 'TUIRIO', 4, 539, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (542, 'TUMUCUMAQUE', 4, 540, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (544, 'TUPIRAMA', 4, 542, 27);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (545, 'VAZANTE', 4, 543, 27);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (546, 'VEADO -"E"', 4, 544, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (547, 'VEADO -AREA C', 4, 545, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (548, 'VERDE', 4, 546, 14);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (549, 'XAVANTE -A', 4, 547, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (550, 'XAVANTE- B', 4, 548, 13);
INSERT INTO tbgleba (cdgleba, nmgleba, tbsubarea_id, id, tbuf_id) VALUES (551, 'XIRIRI', 4, 549, 14);

